/*
----------------
1º FORMA NORMAL
----------------
1 - TODO CAMPO VETORIZADO SE TORANRA OUTRA TABELA
[AZUL, AMARELO, VERDE, VERMELHO]
[KA, FIR, CIVIC, FIESTA]

2 - TODO CAMPO MULTIVALORIZADO SE TORNARA OUTRA TABELA
"RUA MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ"

3 -  TODA TABELA NECESSITA DE PELO MENOS UM CAMPO  QUE
IDENTIFIQUE TODO O REGISTRO COMO SENDO UNICO - CHAMAMOS
DE CHAVE PRIMARIA OU PRIMARY KEY

----------------
CARDINALIDADE
(1,1)
(0,1)
(1,n)
(0,n)
----------------

PRIMEIRO ALGARISMO - OBRIGATORIEDADE
0 - NAO OBRIGATORIO
1 - OBRIGATORIO

SEGUNDO ALGARISMO - OBRIGATORIEDADE
1 - MAXIMO DE UM
N - MAIS DE UM

*/
