
---------------------------------------------------
-- INIT - 001 : SEM MODELAGEM, FORA DA CONVENSÃO
---------------------------------------------------

/* USANDO BANCO */
USE PROJETO;

/* VERIFICANDO A TABELA */
SHOW TABLES;

/* VER ESTRUTURA TABELA */
DESC CLIENTE;

/* INSERÇÃO SEM INFORMAR COLUNAS */
 INSERT INTO CLIENTE VALUES('JOAO', 'M','JOAO@GMAIL.COM',9838274,'971571566', 'MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');
 INSERT INTO CLIENTE VALUES('CELIA', 'F','CELIA@GMAIL.COM',009247811,'971471896', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');
 INSERT INTO CLIENTE VALUES('JORGE', 'M', NULL,012655709,'991571569', 'BELO HORIZONTE - CENTRO - MINAS GERAIS - MG');

/* INSERÇÃO INFORMANDO COLUNAS */
 INSERT INTO CLIENTE (NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES
                           ('LETICIA', 'F', 'MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ','986860055',883246782);

/* INSERÇÃO MULTIPLO E COMPACTO */
 INSERT INTO CLIENTE VALUES('VRONICA', 'F','VERA@BOL.COM',524552811,'971879512', 'PRESIDENTE ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                           ('CARLA', 'F','CARLA@CARLINHA.COM',575567811,'999878519', 'RIBEIRAO DAS NEVES - CENTRO - MINAS GERAIS - MG');

---------------------------------------------------
-- END - 001
---------------------------------------------------

---------------------------------------------------
-- INIT - 002 : COM MODELAGEM, DENTRO DA CONVENSÃO
---------------------------------------------------

/*CLIENTE*/
INSERT INTO CLIENTE VALUES(NULL, 'JOAO',    '98547-6',  'M',  'JOAO@IG.COM');
INSERT INTO CLIENTE VALUES(NULL, 'CARLOS',  '86664-7',  'M',  'CARLOS@TERRA.COM');
INSERT INTO CLIENTE VALUES(NULL, 'ANA',     '75658-5',  'F',  'ANA@GLOBO.COM');
INSERT INTO CLIENTE VALUES(NULL, 'JORGE',   '99657-5',  'M',  'JORGE@IG.COM');
INSERT INTO CLIENTE VALUES(NULL, 'CLARA',   '997754-7', 'F',  NULL);
INSERT INTO CLIENTE VALUES(NULL, 'CELIA',   '77558-5',  'F',  'CELIA@BOL.COM');
INSERT INTO CLIENTE VALUES(NULL, 'ANTONIO', '78558-6',  'M',  NULL);
INSERT INTO CLIENTE VALUES(NULL, 'JOAO',    '86695-6',  'M',  NULL);

/*ENDERECO*/
INSERT INTO ENDERECO VALUES(NULL, 'MG', 'B.HORIZONTE',    'CENTRO',   'RUA A', 2134,  4);
INSERT INTO ENDERECO VALUES(NULL, 'RJ', 'RIO DE JANEIRO', 'CENTRO',   'RUA B', 220,   1);
INSERT INTO ENDERECO VALUES(NULL, 'SP', 'SÃO PAULO',      'JARDINS',  'RUA C', 580,   3);
INSERT INTO ENDERECO VALUES(NULL, 'RJ', 'RIO DE JANEIRO', 'ESTACIO',  'RUA B', 5300,  8);
INSERT INTO ENDERECO VALUES(NULL, 'MG', 'B.HORIZONTE',    'CRUZEIRO', 'RUA Z', 1200,  2);
INSERT INTO ENDERECO VALUES(NULL, 'RJ', 'RIO DE JANEIRO', 'FLAMENGO', 'RUA X', 3000,  7);
INSERT INTO ENDERECO VALUES(NULL, 'MG', 'B.HORIZONTE',    'CRUZEIRO', 'RUA Z', 1201,  5);
INSERT INTO ENDERECO VALUES(NULL, 'RJ', 'NITEROI',        'CENTRO',   'RUA X', 104,   6);

/*TELEFONES*/
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '55', '31', '999553322',  1);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '55', '32', '43553321',   3);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '55', '31', '933443329',  1);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '55', '11', '921586337',  7);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '55', '31', '34253328',   1);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '55', '86', '75553393',   6);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '55', '31', '934557822',  1);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '55', '11', '975553368',  7);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '55', '11', '21555523',   7);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '55', '32', '978553333',  3);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '55', '86', '989534321',  6);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '55', '86', '66558794',   6);


---------------------------------------------------
-- END - 002
---------------------------------------------------