

/* RETORNA DATA E HORA DO BANCO */
SELECT NOW();

/*ALIAS DE COLUNAS, DAR NOME PARA UMA COLUNA*/
SELECT 'FERNANDO'

/* RETORNA ALGUMAS COLUNAS */
SELECT NOME, SEXO, EMAIL FROM CLIENTE;

/* RETORNA TODAS COLUNAS */
SELECT * FROM CLIENTE;


/* FILTRANDO COM WHERE */
SELECT NOME, ENDERECO  FROM CLIENTE
WHERE SEXO = 'N';

/* FILTRANDO COM LIKE = OBS: INIMIGO DA PERFORMACE*/
SELECT NOME, ENDERECO  FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, ENDERECO  FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';