

/* RETORNA DATA E HORA DO BANCO */
SELECT NOW();

/*ALIAS DE COLUNAS, DAR NOME PARA UMA COLUNA*/
SELECT 'FERNANDO'

/* RETORNA ALGUMAS COLUNAS */
SELECT NOME, SEXO, EMAIL FROM CLIENTE;

/* RETORNA TODAS COLUNAS */
SELECT * FROM CLIENTE;


/* FILTRANDO COM WHERE */
SELECT NOME, ENDERECO  FROM CLIENTE
WHERE SEXO = 'N';

/* FILTRANDO COM LIKE = OBS: INIMIGO DA PERFORMACE*/
SELECT NOME, ENDERECO  FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, ENDERECO  FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';

/*
============================
  FILTRANDO TABELA VERDADE
----------------------------
   A   B   A ou B  A e B
   V   V     V       V
   V   F     V       F
   F   V     V       F
   F   F     F       F
*===========================/

/*OR - OU */
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'M' OR ENDERECO LIKE '%RJ';

/*AND - E */
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'M' AND ENDERECO LIKE '%MG';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'f' AND ENDERECO LIKE '%ESTACIO%';
