
SELECT NOME, SEXO, EMAIL FROM CLIENTE;

-- UPDATE SEMPRE COM CLAUSULA WHERE

/*
MARIA ESTA COM SEXO = M
ALTERAR PARA F
*/
UPDATE CLIENTE
SET SEXO = "F"
WHERE NOME = "MARIA";

/* CORRIGINDO NOME VRONICA PARA VERONICA */
UPDATE CLIENTE
SET NOME = "VERONICA"
WHERE EMAIL = "VERA@BOL.COM";