
/* USANDO BANCO */
USE PROJETO;

/* CRIANDO TABELA */
CREATE TABLE CLIENTE(
  NOME VARCHAR(150),
  SEXO CHAR(1),
  EMAIL VARCHAR(30),
  CPF INT (11),
  TELEFONE VARCHAR(30),
  ENDERECO VARCHAR(100)
);

/* VERIFICANDO A TABELA */
SHOW TABLES;

/* VER ESTRUTURA TABELA */
DESC CLIENTE;
